name: flutter_frontend_vote
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  chewie: ^1.12.1
  dio: ^5.8.0+1
  get_storage: ^2.1.1
  hive_flutter: ^1.1.0
  socket_io_client: ^3.1.4
  iconsax: ^0.0.8
  # eip55: ^1.0.3
  ethereum_addresses: ^1.0.2
  file_picker: ^10.2.0
  fl_chart: ^1.0.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.4
  form_validator: ^2.1.1
  freezed_annotation: ^3.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  go_router: ^16.0.0
  # google_mlkit_face_detection: ^0.11.1
  # google_mlkit_object_detection: ^0.13.1
  # google_mlkit_text_recognition: ^0.13.0
  flutter_face_api: ^7.1.298
  flutter_slidable: ^4.0.0
  local_auth: ^2.3.0
  permission_handler: ^12.0.1
  percent_indicator: ^4.2.5
  syncfusion_flutter_charts: ^30.1.41
  smooth_page_indicator: ^1.2.0+3
  walletconnect_dart: ^0.0.11
  web3dart: ^2.7.0
  video_player: ^2.10.0
  url_launcher: ^6.3.2
  carousel_slider: ^5.0.0
  uuid: ^3.0.5
  share_plus: ^11.0.0
  wakelock_plus: ^1.2.8
  pull_to_refresh: ^2.0.0
  flutter_dotenv: ^6.0.0
  cached_network_image: ^3.2.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.1
  logger: ^2.5.0
  get_it: ^8.0.3

  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.4
  firebase_messaging: ^15.2.10
  flutter_callkit_incoming: ^2.0.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0

  flutter_lints: ^5.0.0

# use 3 rows from every corner for equal shaped icon
flutter_launcher_icons:
  android: true
  image_path_android: assets/logo/icon6.png
  android_adaptive_icon_background: "#F7FAFC"
  android_adaptive_icon_foreground: assets/logo/icon6.png
  adaptive_icon_background: "#F7FAFC"
  # For iOS, we use a different image and background color
  ios: true
  image_path_ios: assets/logo/icon6.png
  background_color_ios: "#F7FAFC"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
