# ============================================================================
# VoteSecure — Kubernetes Namespace
# ============================================================================
apiVersion: v1
kind: Namespace
metadata:
  name: votesecure
  labels:
    app: votesecure-api
    project: votesecure-decentralized-vote
    environment: production
